### ISSUE TITLE
Feature request - GTK3 Fedora Blue-Submarine Theme

### ISSUE THREAD

**Issue by NiceandGently** [NiceandGently/mate-themes-extras#5]
from https://github.com/mate-desktop/mate-themes/issues/86
Hello, would it be possible to have the more minimal panel handle style from the GTK2 version of Blue-Submarine in GTK3? I'm not a huge fan of the chunkier full height dimpled handles and they don't work with a transparent panel background very nicely.

**Comment by NiceandGently** [comment]
Hi Mike,
i forgot to add the icon to bluementa theme in fedora package.
https://github.com/mate-desktop/mate-themes/commit/bb954591f3d1cc5c0aa226d158ac73437e01d7a8
So you couldn't see the grid image.
Yes, my intention was already to support full transparency in themes.
I've re-work submarine's themes panel configuration today. See
https://github.com/NiceandGently/mate-themes-extras/commit/1ce5c0ed1777c21537d0cd097025719a4c69b24f
You can simply replace the new settings into /usr/share/themes/Blue-Submarine/gtk-3.0/mate-applications.css
https://github.com/NiceandGently/mate-themes-extras/blob/1ce5c0ed1777c21537d0cd097025719a4c69b24f/desktop-themes/Blue-Submarine/gtk-3.0/mate-applications.css#L615
Line 615 - 900
Don't foget to copy https://github.com/NiceandGently/mate-themes-extras/blob/master/desktop-themes/Blue-Submarine/gtk-3.0/assets/panel-grid.svg
to /usr/share/themes/Blue-Submarine/gtk-3.0/assets
and reload the theme.
Feel free to test this, i hope you like it.
You can simply replace the image by another one with same name.
The icon is a symbolic icon which works great on all kinds of desktop backgrounds and with transparency.
The icon format is 12 x 22.
But , as i said i'm willing to add another one if it works on transparency and normal panel.
Maybe you need to adjust this line if don't see your image
https://github.com/NiceandGently/mate-themes-extras/blob/master/desktop-themes/Blue-Submarine/gtk-3.0/mate-applications.css#L673
background-position: left;
Here left, right, top, bottom and center is possible.

**Comment by arehtykitna** [comment]
Hi, the modifications worked perfectly thanks. I've tried out the panel-grid.svg and it works okay. It could do with being a little darker for the Submarine themes. Substituting the fill value for the 3 rectangles in the panel-grid.svg #bebebe for #555555 seems to work as illustrated by the attached.
![screenshot](https://cloud.githubusercontent.com/assets/7422283/7988924/e67106b4-0add-11e5-97f5-d381f4b6b991.png)

**Comment by NiceandGently** [comment]
Looks good,
can you please send me the image?
....as i said i'm totally bad in using image progarams :)

**Comment by arehtykitna** [comment]
Hi, no problem, I'll email it to you. I can't attach it here in SVG format.

**Comment by NiceandGently** [comment]
Thank you Mike
https://github.com/NiceandGently/mate-themes-extras/commit/705e9324a2c9883fc69e968c93f3287bd64943ed
